
import '../model/Meal_item.dart';
import '../model/Category_model.dart';

List<MealsItem> meals = [
  MealsItem(
      id: "m1",
      title: "LAMP CHOPS",
      imageUrl: "assets/images/lampchops.jpg",
      salary: "150",
      time: "35",
      description: "Fillet Steak round 275gm, topped with brown pepper sauce served with your choice of 2 sides",
      categoryNumber: "c3"),
  MealsItem(
      id: "m2",
      title: "BUTTER CHICKEN",
      imageUrl: "assets/images/butterchicken.jpg",
      salary: "90",
      time: "25",
      description: "Tender chicken cooked in a rich and creamy tomato butter sauce, served with rice or naan.",
      categoryNumber: "c2"),
  MealsItem(
      id: "m3",
      title: "ALFREDO",
      imageUrl: "assets/images/alfredo.jpg",
      salary: "60",
      time: "25",
      description: "Creamy Alfredo pasta tossed with grilled chicken and parmesan cheese.",
      categoryNumber: "c4"),
  MealsItem(
      id: "m4",
      title: "Steak",
      imageUrl: "assets/images/steak.jpg",
      salary: "150",
      time: "30",
      description: "Juicy grilled steak cooked to perfection, served with your choice of two sides.",
      categoryNumber: "c3"),
  MealsItem(
      id: "m5",
      title: "Smoked Cheesy",
      imageUrl: "assets/images/smoked_cheesy.jpg",
      salary: "90",
      time: "25",
      description: "Smoked beef patty topped with melted cheese, grilled onions, and special sauce.",
      categoryNumber: "c7"),
  MealsItem(
      id: "m6",
      title: "Lamp Biryani",
      imageUrl: "assets/images/lamp_biryani.jpg",
      salary: "90",
      time: "30",
      description: "Flavorful rice dish cooked with tender lamb pieces and aromatic spices.",
      categoryNumber: "c2"),
  MealsItem(
      id: "m7",
      title: "ShiSh Tawook Rice",
      imageUrl: "assets/images/shish_Tawook.jpg",
      salary: "99",
      time: "30",
      description: "Grilled marinated chicken skewers served over spiced rice and garlic sauce.",
      categoryNumber: "c7"),
  MealsItem(
      id: "m8",
      title: "Lamp Shank",
      imageUrl: "assets/images/lamp_shank.jpg",
      salary: "130",
      time: "35",
      description: "Slow-cooked lamb shank in rich gravy served with mashed potatoes or rice.",
      categoryNumber: "c3"),
  MealsItem(
      id: "m9",
      title: "Sweet & Sour Chicken",
      imageUrl: "assets/images/sweet_chilli.jpg",
      salary: "95",
      time: "30",
      description: "Crispy chicken pieces in sweet and sour sauce with bell peppers and pineapple.",
      categoryNumber: "c2"),
  MealsItem(
      id: "m10",
      title: "Chicken Tikka Masala",
      imageUrl: "assets/images/indian.jpg",
      salary: "120",
      time: "35",
      description: "Chunks of grilled chicken in a creamy spiced tomato sauce served with basmati rice.",
      categoryNumber: "c3"),
  MealsItem(
      id: "m11",
      title: "Beef Oriental",
      imageUrl: "assets/images/oriental.jpg",
      salary: "110",
      time: "30",
      description: "Stir-fried beef with vegetables in oriental sauce served with noodles.",
      categoryNumber: "c4"),
  MealsItem(
      id: "",
      title: "Creamy Mushroom Pasta",
      imageUrl: "assets/images/pasta.jpg",
      salary: "70",
      time: "25",
      description: "Penne pasta with creamy mushroom sauce and parmesan cheese.",
      categoryNumber: ""),
  MealsItem(
      id: "m13",
      title: "Crispy Chicken ",
      imageUrl: "assets/images/sand.jpg",
      salary: "65",
      time: "20",
      description: "Fried chicken sandwich with lettuce, tomato, and spicy mayo.",
      categoryNumber: "c6"),
  MealsItem(
      id: "m14",
      title: "Greek Salad",
      imageUrl: "assets/images/salad.jpg",
      salary: "55",
      time: "15",
      description: "Fresh cucumber, tomato, olives, and feta cheese tossed with vinaigrette.",
      categoryNumber: "c7"),
  MealsItem(
      id: "m15",
      title: "Kabsa Rice",
      imageUrl: "assets/images/Rice.jpg",
      salary: "95",
      time: "30",
      description: "Traditional Middle Eastern rice with spiced chicken and almonds.",
      categoryNumber: "c8"),
  MealsItem(
      id: "m16",
      title: "Chocolate Lava Cake",
      imageUrl: "assets/images/desatr.jpg",
      salary: "45",
      time: "15",
      description: "Warm chocolate cake with molten chocolate center served with ice cream.",
      categoryNumber: "c9"),
];


List<CategoryItem> MealsCategories = [
  CategoryItem(id: 'c2', name: "Chinese", image: "assets/images/chinese.jpg"),
  CategoryItem(id: 'c3', name: "Indian", image: "assets/images/indian.jpg"),
  CategoryItem(id: 'c4', name: "Oriental Meals", image: "assets/images/oriental.jpg"),
  CategoryItem(id: 'c5', name: "Pasta", image: "assets/images/pasta.jpg"),
  CategoryItem(id: 'c6', name: "Sandwich", image: "assets/images/sand.jpg"),
  CategoryItem(id: 'c7', name: "Salads", image: "assets/images/salad.jpg"),
  CategoryItem(id: 'c8', name: "Rice Dishes", image: "assets/images/Rice.jpg"),
  CategoryItem(id: 'c9', name: "Dessert", image: "assets/images/desatr.jpg"),
];

